add missing field name 'lang'
Fix NotSupportedError exception which appears when searching fields by
description:
NotSupportedError: input of anonymous composite types is not implemented
"LINE 1: ...ND ir_translation.res_id = 0 AND ir_translation = E'en_US' A..."

issue2210
review158001
(transplanted from 5315ef978e92158ea5460e83ed5f94a4717a463d)

--HG--
extra : transplant_source : S%15%EF%97%8E%92%15%8E%A5F%0E%83%ED_%94%A4qzF%3D