add missing field name 'lang'
Fix NotSupportedError exception which appears when searching fields by
description:
NotSupportedError: input of anonymous composite types is not implemented
"LINE 1: ...ND ir_translation.res_id = 0 AND ir_translation = E'en_US' A..."

issue2210
review158001